version: "3"
services:
  api:
    build: .
    image: pmsapi
    ports:
      - "8080:8080"
    volumes:
      - ./cont_logs:/app/logs
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:9000/thedynamicdoersdb?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.password": "root"
      }'
    restart: on-failure
